apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/everisopennetworks/dso-pc-chart-prometheus.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/eks-devops-prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
